# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 19:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_product_category', models.IntegerField()),
                ('product_category_name', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Discriptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_discription', models.IntegerField()),
                ('s_discription', models.CharField(max_length=500)),
                ('l_discription', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Feed_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_feed_type', models.IntegerField()),
                ('feed_type_name', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_menu', models.IntegerField()),
                ('menu_name', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Pictures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_picture', models.IntegerField()),
                ('main_picture', models.CharField(max_length=500)),
                ('picture', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Pictures_has_Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_picture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cookbook.Pictures')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_product', models.IntegerField()),
                ('product_name', models.CharField(max_length=45)),
                ('product_calories', models.IntegerField()),
                ('gmo', models.BooleanField()),
                ('id_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cookbook.Category')),
                ('id_discription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cookbook.Discriptions')),
            ],
        ),
        migrations.CreateModel(
            name='Product_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_category', models.IntegerField()),
                ('category_name', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Product_has_Pictures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_picture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cookbook.Pictures')),
                ('id_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cookbook.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Product_has_Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField()),
                ('weight_type', models.CharField(max_length=45)),
                ('id_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cookbook.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_recipe', models.IntegerField()),
                ('recipe_name', models.CharField(max_length=45)),
                ('recipe_calories', models.IntegerField()),
                ('cooking_time', models.IntegerField()),
                ('number_of_servings', models.IntegerField()),
                ('Rating', models.CharField(max_length=45)),
                ('Steps', models.CharField(max_length=2000)),
                ('Creation_date', models.DateTimeField()),
                ('id_discription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cookbook.Discriptions')),
                ('id_feed_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cookbook.Feed_type')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_recipe_category', models.IntegerField()),
                ('recipe_category_name', models.CharField(max_length=45)),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='id_recipe_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cookbook.Recipe_category'),
        ),
        migrations.AddField(
            model_name='product_has_recipe',
            name='id_recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cookbook.Recipe'),
        ),
        migrations.AddField(
            model_name='pictures_has_recipe',
            name='id_recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cookbook.Recipe'),
        ),
        migrations.AddField(
            model_name='menu',
            name='id_recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cookbook.Recipe'),
        ),
    ]
