# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-28 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='product_category_name',
            new_name='category_name',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='id_product_category',
            new_name='id_category',
        ),
        migrations.RenameField(
            model_name='product_category',
            old_name='id_category',
            new_name='id_product_category',
        ),
        migrations.RenameField(
            model_name='product_category',
            old_name='category_name',
            new_name='product_category_name',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='Rating',
            field=models.IntegerField(default=0),
        ),
    ]
