# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-02 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0003_auto_20170602_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='get_recipe',
            name='group_of_product',
            field=models.CharField(default=0, max_length=45),
        ),
        migrations.AddField(
            model_name='get_recipe',
            name='main_recipe_discription',
            field=models.CharField(default=0, max_length=500),
        ),
        migrations.AlterField(
            model_name='get_recipe',
            name='product_category_name',
            field=models.CharField(default=0, max_length=45),
        ),
    ]
